#ifndef SCREEN_H_INCLUDED
#define SCREEN_H_INCLUDED

#define GAME_AREA_WIDTH 800
#define GAME_AREA_HEIGHT 600
#define SCREEN_WIDTH GAME_AREA_WIDTH
#define SCREEN_HEIGHT GAME_AREA_HEIGHT + UI_OFFSET
#define UI_OFFSET 100
#define UI_HEADER_SIZE (UI_OFFSET / 2) + 10

#endif // SCREEN_H_INCLUDED